/**
 * All user-facing UI string literals live here (localization-ready per
 * Founder Decision 11). No inline user-facing text in components.
 * When a second language is scheduled, this module becomes the default
 * message catalog for next-intl.
 */
export const strings = {
  brand: {
    name: "AIQ",
    tagline: "AI Work Style & Readiness Assessment",
  },
  landing: {
    heroTitle: "Discover how you really work with AI",
    heroSubtitle:
      "A 3-minute behavioral assessment that reveals your AI work style — not how much jargon you know.",
    cta: "Start the assessment",
    ctaSecondary: "Sign in",
    noSignupNote: "No account needed to start.",
  },
  auth: {
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your AIQ account",
    signupTitle: "Create your account",
    signupSubtitle: "See your results and track your progress",
    resetTitle: "Reset your password",
    resetSubtitle: "We'll email you a reset link",
    emailLabel: "Email",
    passwordLabel: "Password",
    fullNameLabel: "Full name",
    loginAction: "Sign in",
    signupAction: "Create account",
    resetAction: "Send reset link",
    resetSent: "Check your email for a reset link.",
    toSignup: "New to AIQ? Create an account",
    toLogin: "Already have an account? Sign in",
    toReset: "Forgot your password?",
    signOut: "Sign out",
  },
  dashboard: {
    title: "Dashboard",
    emptyTitle: "No assessments yet",
    emptyBody: "Take your first assessment to discover your AI work style.",
    emptyAction: "Start the assessment",
    currentProfile: "Your current profile",
    viewResults: "View full results",
    history: "Progress over time",
    historyHint: "Your newest result is your profile. Retake every 30 days.",
    retakeAction: "Retake the assessment",
    retakeLockedPrefix: "Next retake available",
  },
  assessment: {
    introNote:
      "No account needed. Takes about 3 minutes. No right answers — answer honestly.",
    start: "Begin",
    startError: "Could not start the assessment. Please try again.",
  },
  runner: {
    back: "Back",
    next: "Next",
    submit: "See my results",
    answered: "answered",
    progressLabel: "Assessment progress",
    keyHint: "Press 1–4 to answer · arrows to navigate",
  },
  retake: {
    lockedTitle: "You've completed this assessment",
    lockedBody: "Retake available on",
    viewResults: "View your latest results",
  },
  claim: {
    title: "Your results are ready",
    subtitle: "Create your free account to see your AI work style profile.",
    convertAction: "Create account & see results",
    haveAccount: "Already have an account? Sign in to attach these results",
    continueAction: "View my results",
    continueTitle: "Welcome back",
    continueSubtitle: "Your assessment is complete.",
  },
  results: {
    title: "Your results",
    overall: "Overall score",
    persona: "Your AI work style",
    competencies: "Competency profile",
    strengths: "Strengths",
    blindSpots: "Blind spots",
    confidence: "Profile confidence",
    confidenceLow: "We need more information to build an accurate profile.",
    notMeasured: "Not measured",
    noneYet: "None identified in this session.",
  },
  admin: {
    title: "Admin",
    nav: {
      questions: "Questions",
      competencies: "Competencies",
      personas: "Personas",
      assessments: "Assessments",
    },
    dashboard: {
      subtitle: "Manage the platform's content — no SQL required.",
    },
    common: {
      newItem: "New",
      save: "Save",
      saving: "Saving…",
      edit: "Edit",
      publish: "Publish",
      unpublish: "Unpublish",
      archive: "Archive",
      restore: "Restore to draft",
      status: "Status",
      name: "Name",
      slug: "Slug",
      slugHint: "lowercase-kebab-case; cannot be changed after creation",
      description: "Description",
      displayOrder: "Display order",
      saved: "Saved.",
      empty: "Nothing here yet.",
    },
    questions: {
      title: "Questions",
      newTitle: "New question",
      editTitle: "Edit question",
      questionTitle: "Title",
      scenario: "Scenario",
      difficulty: "Difficulty (1–5)",
      tags: "Industry tags (comma-separated)",
      options: "Answer options",
      optionContent: "Option text",
      signals: "Behavioral signals",
      addSignal: "Add signal",
      removeSignal: "Remove",
      addOption: "Add option",
      removeOption: "Remove option",
      weight: "Weight",
      competency: "Competency",
      publishBlocked: "Cannot publish yet:",
      publishWarnings: "Published with warnings:",
      published: "Question published.",
      immutableNote:
        "This question has recorded responses and is locked — archive it and author a replacement.",
      version: "v",
    },
    assessments: {
      title: "Assessments",
      questionsReady: "published questions",
    },
  },
  errors: {
    genericTitle: "Something went wrong",
    genericBody: "An unexpected error occurred. Please try again.",
    retry: "Try again",
    notFoundTitle: "Page not found",
    notFoundBody: "The page you're looking for doesn't exist.",
    goHome: "Go home",
    authFailed: "Sign-in failed. Check your email and password.",
    signupFailed: "Could not create your account. Please try again.",
    invalidInput: "Please check the highlighted fields.",
  },
} as const;
