/**
 * All user-facing UI string literals live here (localization-ready per
 * Founder Decision 11). No inline user-facing text in components.
 * When a second language is scheduled, this module becomes the default
 * message catalog for next-intl.
 */
export const strings = {
  brand: {
    name: "AIQ",
    tagline: "AI Work Style & Readiness Assessment",
  },
  landing: {
    heroTitle: "What kind of AI user are you?",
    heroSubtitle:
      "Everyone uses AI differently. 8 everyday work moments. 3 minutes. Find out.",
    cta: "Find out",
    ctaSecondary: "Sign in",
    noSignupNote: "No account needed to start.",
    whichOne: "One of these is you.",
  },
  auth: {
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your AIQ account",
    signupTitle: "Create your account",
    signupSubtitle: "See your results and track your progress",
    resetTitle: "Reset your password",
    resetSubtitle: "We'll email you a reset link",
    emailLabel: "Email",
    passwordLabel: "Password",
    fullNameLabel: "Full name",
    loginAction: "Sign in",
    signupAction: "Create account",
    resetAction: "Send reset link",
    resetSent: "Check your email for a reset link.",
    updateTitle: "Choose a new password",
    updateSubtitle: "You're signed in \u2014 set your new password below.",
    newPasswordLabel: "New password",
    updateAction: "Save new password",
    updated: "Password updated \u2014 you're all set.",
    linkError: "That link is invalid or has expired. Request a new one below.",
    toSignup: "New to AIQ? Create an account",
    toLogin: "Already have an account? Sign in",
    toReset: "Forgot your password?",
    signOut: "Sign out",
  },
  dashboard: {
    title: "Dashboard",
    emptyTitle: "Your style is waiting",
    emptyBody:
      "Three minutes, eight everyday work moments — find your AI work style.",
    emptyAction: "Find out",
    currentProfile: "Your current profile",
    viewResults: "View full results",
    history: "Your journey",
    historyHint: "Your newest result is your profile.",
    retakeAction: "Take it again",
    retakeLockedPrefix: "Your next evolution unlocks",
  },
  assessment: {
    introNote: "8 everyday work moments. Just pick what you'd actually do.",
    introMeta: "3 minutes · no account needed",
    start: "Let's find out",
    startError: "Something went wrong starting — please try again.",
  },
  runner: {
    back: "Back",
    next: "Next",
    milestones: {
      3: "Interesting choices\u2026",
      5: "Your style is taking shape.",
      8: "Last one \u2014 your reveal is next.",
    } as Record<number, string>,
    submit: "Reveal my work style",
    answered: "answered",
    normallyDo: "What would you normally do?",
    progressLabel: "Your progress",
    keyHint: "Press 1–4 to answer · arrows to navigate",
  },
  reveal: {
    stages: ["Reading your 8 choices…", "Mapping your work style…", "Ready."],
  },
  share: {
    action: "Share my work style",
    copied: "Link copied — paste it anywhere.",
    message: "I got {persona}! What kind of AI user are you?",
  },
  retake: {
    lockedTitle: "You've already revealed your style",
    lockedBody: "Your next evolution unlocks",
    viewResults: "View your latest results",
  },
  claim: {
    title: "Your work style is in.",
    subtitle:
      "One step from the reveal \u2014 create your free account to open it.",
    convertAction: "Create account & see results",
    haveAccount: "Already have an account? Sign in to attach these results",
    continueAction: "View my results",
    continueTitle: "Welcome back",
    continueSubtitle: "Your work style is ready.",
  },
  certificate: {
    sectionTitle: "Your certificate",
    download: "Download certificate (PDF)",
    copyLink: "Copy verification link",
    copied: "Link copied.",
    storyImage: "Story image",
    shareHint:
      "Anyone with the link sees your work style and date — never your scores.",
  },
  verify: {
    title: "Certificate verification",
    valid: "Valid certificate",
    revoked: "This certificate has been revoked",
    notFoundTitle: "Certificate not found",
    notFoundBody: "This verification code doesn't match any AIQ certificate.",
    holder: "Issued to",
    persona: "AI work style",
    issued: "Issued",
    assessment: "Assessment",
    cta: "Discover your own AI work style",
  },
  results: {
    title: "Your results",
    superpower: "Superpower",
    continue: "Keep it forever",
    persona: "Your AI work style",
  },
  admin: {
    title: "Admin",
    nav: {
      questions: "Questions",
      competencies: "Competencies",
      personas: "Personas",
      assessments: "Assessments",
    },
    dashboard: {
      subtitle: "Manage the platform's content — no SQL required.",
    },
    common: {
      newItem: "New",
      save: "Save",
      saving: "Saving…",
      edit: "Edit",
      publish: "Publish",
      unpublish: "Unpublish",
      archive: "Archive",
      restore: "Restore to draft",
      status: "Status",
      name: "Name",
      slug: "Slug",
      slugHint: "lowercase-kebab-case; cannot be changed after creation",
      description: "Description",
      displayOrder: "Display order",
      saved: "Saved.",
      empty: "Nothing here yet.",
    },
    questions: {
      title: "Questions",
      newTitle: "New question",
      editTitle: "Edit question",
      questionTitle: "Title",
      scenario: "Scenario",
      difficulty: "Difficulty (1–5)",
      tags: "Industry tags (comma-separated)",
      options: "Answer options",
      optionContent: "Option text",
      signals: "Behavioral signals",
      addSignal: "Add signal",
      removeSignal: "Remove",
      addOption: "Add option",
      removeOption: "Remove option",
      weight: "Weight",
      competency: "Competency",
      publishBlocked: "Cannot publish yet:",
      publishWarnings: "Published with warnings:",
      published: "Question published.",
      immutableNote:
        "This question has recorded responses and is locked — archive it and author a replacement.",
      version: "v",
    },
    assessments: {
      title: "Assessments",
      questionsReady: "published questions",
    },
  },
  errors: {
    genericTitle: "Something went wrong",
    genericBody: "An unexpected error occurred. Please try again.",
    retry: "Try again",
    notFoundTitle: "Page not found",
    notFoundBody: "The page you're looking for doesn't exist.",
    goHome: "Go home",
    authFailed: "Sign-in failed. Check your email and password.",
    signupFailed: "Could not create your account. Please try again.",
    invalidInput: "Please check the highlighted fields.",
  },
} as const;
